Repository SecureTrading/js-payments, pull requests merged in 2019-12, with the labels that each got.

#586 feature/ST-443-provide-translated-labels-to-js-payments-card
  example/index.html
  src/ST.ts
  src/components/animated-card/animated-card.ts
  src/json/config.json
Labels: enhancement, javascript

#585 Hotfix/serialize javascript vulnerability
  package-lock.json
  package.json
Labels: bug, javascript

#591 feature/ST-451-validation-class-code-improvements
  src/components/card-number/CardNumber.ts
  src/components/control-frame/ControlFrame.ts
  src/components/expiration-date/ExpirationDate.ts
  src/components/notification-frame/NotificationFrame.ts
  src/components/security-code/SecurityCode.ts
  src/core/classes/MerchantFields.ts
  src/core/shared/FormField.ts
  src/core/shared/Frame.ts
  src/core/shared/Validation.ts
  src/json/config.json
  test/core/shared/Frame.spec.ts
Labels: enhancement, javascript

#589 feature/ST-450-card-frame-class-code-improvements
  src/components/card-number/CardNumber.ts
  src/components/control-frame/ControlFrame.ts
  src/components/expiration-date/ExpirationDate.ts
  src/components/notification-frame/NotificationFrame.ts
  src/components/security-code/SecurityCode.ts
  src/core/classes/CardFrames.class.ts
  src/core/classes/MerchantFields.ts
  src/core/classes/RegisterFrames.class.ts
  src/core/models/CardFrames.ts
  src/core/models/MessageBusEvent.ts
  src/core/shared/FormField.ts
  src/core/shared/Frame.ts
  src/core/shared/Validation.ts
  src/json/config.json
  test/core/classes/CardFrames.spec.ts
  test/core/shared/Frame.spec.ts
Labels: enhancement, javascript

#547 feature/ST-357-allow-returning-customer-to-only-submit-securitycode
  example/index.html
  package-lock.json
  package.json
  src/ST.ts
  src/components/card-number/CardNumber.ts
  src/components/control-frame/ControlFrame.ts
  src/components/expiration-date/ExpirationDate.ts
  src/components/notification-frame/NotificationFrame.ts
  src/components/security-code/SecurityCode.ts
  src/core/classes/CardFrames.class.ts
  src/core/classes/MerchantFields.ts
  src/core/classes/RegisterFrames.class.ts
  src/core/integrations/CardinalCommerce.ts
  src/core/models/CardFrames.ts
  src/core/models/Config.ts
  src/core/models/ControlFrame.ts
  src/core/models/MessageBusEvent.ts
  src/core/shared/FormField.ts
  src/core/shared/Frame.ts
  src/core/shared/MessageBus.ts
  src/core/shared/Validation.ts
  src/json/config.json
  test/components/card-number/CardNumber.spec.ts
  test/components/control-frame/ControlFrame.spec.ts
  test/core/classes/CardFrames.spec.ts
  test/core/classes/RegisterFrames.spec.ts
  test/core/shared/FormField.spec.ts
  test/core/shared/Formatter.spec.ts
  test/core/shared/Frame.spec.ts
  test/core/shared/Validation.spec.ts
Labels: enhancement, javascript

#592 Hotfix for ensuring cardinal js and listeners are only added once
  CHANGELOG.md
  Dockerfile
  package-lock.json
  src/core/integrations/CardinalCommerce.ts
  test/core/integrations/CardinalCommerce.spec.ts
Labels: bug, javascript

#599 feature/ST-400-control-frame-ut
  src/components/card-number/CardNumber.ts
  src/components/control-frame/ControlFrame.ts
  src/core/integrations/ApplePay.ts
  src/core/integrations/CardinalCommerce.ts
  src/core/models/ControlFrame.ts
  src/core/shared/FormField.ts
  src/core/shared/FormFieldState.ts
  src/core/shared/Validation.ts
  src/json/config.json
  test/components/control-frame/ControlFrame.spec.ts
Labels: javascript

#613 fix/ST-357-card-frames-fix
  .gitignore
  babel.config.js
  package.json
  src/ST.ts
  src/core/classes/CardFrames.class.ts
  src/core/shared/Language.ts
  src/core/translations/cy_GB.json
  src/core/translations/da_DK.json
  src/core/translations/de_DE.json
  src/core/translations/en_GB.json
  src/core/translations/en_US.json
  src/core/translations/es_ES.json
  src/core/translations/fr_FR.json
  src/core/translations/nl_NL.json
  src/core/translations/no_NO.json
  src/core/translations/sv_SE.json
  src/json/config.json.dist
  test/core/classes/CardFrames.spec.ts
Labels: bug, javascript
