Repository SecureTrading/js-payments, pull requests merged in 2020-01, with the labels that each got.

#649 feature/ST-348-refactor-merchant-fields-class
  src/ST.ts
  src/components/card-number/CardNumber.ts
  src/core/classes/MerchantFields.ts
  src/core/shared/FormField.ts
  src/core/shared/Validation.ts
  src/json/config.json
  test/components/card-number/CardNumber.spec.ts
  test/core/classes/MerchantFields.spec.ts
  test/core/shared/Validation.spec.ts
Labels: enhancement, javascript

#697 release/2.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/json/config.json
Labels: dependencies, javascript

#709 bugfix/failing-pipeline-typescript-issue
  README.md
  package-lock.json
  package.json
  webpack.dev.js
  webpack.test.js
Labels: bug, javascript

#654 feature/ST-422-change-library-target-to-umd
  example/index.html
  example/init.ts
  src/json/config.json
  webpack.common.js
Labels: enhancement, javascript

#712 Fix for missing . for class in dom selector
  src/components/notification-frame/NotificationFrame.ts
Labels: bug, javascript

#711 Feature/st 431 add config for remaining browser
  .travis.yml
Labels: enhancement, security
