Repository SecureTrading/js-payments, pull requests merged in 2020-03, with the labels that each got.

#810 use try/catch for configurationInit
  example/index.html
Labels: enhancement, javascript

#792 bugfix/ST-549-updateJWT-doesnt-work-correctly-with-frictionless-3DS-payment
  example/index.html
  src/components/card-number/CardNumber.ts
  src/core/config/ConfigResolver.ts
  src/core/config/schema/ConfigSchema.ts
  src/core/integrations/CardinalCommerce.ts
  src/core/integrations/CardinalCommerceMock.ts
  src/core/models/constants/PaymentEvents.ts
  src/core/shared/Payment.ts
  test/components/card-number/CardNumber.spec.ts
  test/core/integrations/CardinalCommerce.spec.ts
Labels: bug, javascript

#833 feature/ST-495-ie-fix
  example/index.html
  package-lock.json
  src/components/card-number/CardNumber.ts
  src/components/control-frame/ControlFrame.ts
  src/components/control-frame/control-frame.ts
  src/components/expiration-date/ExpirationDate.ts
  src/components/notification-frame/notification-frame.ts
  src/components/security-code/SecurityCode.ts
  src/core/classes/CardFrames.class.ts
  src/core/config/ConfigProvider.ts
  src/core/config/ConfigService.ts
  src/core/config/model/IConfig.ts
  src/core/config/model/IPlaceholdersConfig.ts
  src/core/services/message-bus/FramesHub.ts
  src/core/services/message-bus/InterFrameCommunicator.ts
  src/core/services/message-bus/messages/ResponseMessage.ts
  src/core/services/storage/AbstractStorage.ts
  src/core/shared/MessageBus.ts
  src/core/shared/Validation.ts
  src/core/shared/utils/Uuid.ts
  src/json/config.json
  test/components/card-number/CardNumber.spec.ts
  test/components/expiration-date/ExpirationDate.spec.ts
  test/components/security-code/SecurityCode.spec.ts
  webpack.common.js
Labels: bug, javascript

#822 [WIP] feature/ST-495-allow-placeholder-to-be-overridden-by-merchant-configuration
  example/index.html
  package-lock.json
  src/components/card-number/CardNumber.ts
  src/components/card-number/card-number.ts
  src/components/control-frame/ControlFrame.ts
  src/components/control-frame/control-frame.ts
  src/components/expiration-date/ExpirationDate.ts
  src/components/expiration-date/expiration-date.ts
  src/components/notification-frame/notification-frame.ts
  src/components/security-code/SecurityCode.ts
  src/components/security-code/security-code.ts
  src/core/classes/CardFrames.class.ts
  src/core/config/ConfigProvider.ts
  src/core/config/ConfigResolver.ts
  src/core/config/model/IConfig.ts
  src/core/config/model/IPlaceholdersConfig.ts
  src/core/config/schema/ConfigSchema.ts
  src/core/models/IPlaceholdersConfig.ts
  src/core/services/message-bus/FramesHub.ts
  src/core/services/message-bus/InterFrameCommunicator.ts
  src/core/services/message-bus/messages/ResponseMessage.ts
  src/core/services/storage/AbstractStorage.ts
  src/core/shared/FormField.ts
  src/core/shared/MessageBus.ts
  src/core/shared/Validation.ts
  src/core/shared/utils/Uuid.ts
  src/json/config.json
  test/components/card-number/CardNumber.spec.ts
  test/components/expiration-date/ExpirationDate.spec.ts
  test/components/security-code/SecurityCode.spec.ts
  webpack.common.js
Labels: enhancement, javascript

#817 Added build name to environment
  .travis.yml
Labels: enhancement

#801 feature/ST-498-add-payment-icon-to-credit-card
  package-lock.json
  package.json
  src/components/card-number/CardNumber.ts
  src/core/config/ConfigResolver.ts
  src/core/config/model/IConfig.ts
  src/core/config/schema/ConfigSchema.ts
  src/core/models/IBinLookupConfigType.ts
  src/core/models/ICardType.ts
  src/core/models/IIconAttributes.ts
  src/core/models/IIconMap.ts
  src/core/services/icon/IconFactory.ts
  src/core/services/icon/IconMap.ts
  src/core/styles/_core.scss
  src/images/amex.png
  src/images/astropaycard.png
  src/json/config.json
  test/components/card-number/CardNumber.spec.ts
Labels: enhancement, javascript

#816 feature/ST-545-allow-merchant-to-not-include-notification-frame
  package-lock.json
  src/components/control-frame/ControlFrame.ts
  src/core/classes/StCodec.class.ts
  src/core/config/ConfigResolver.ts
  src/core/config/model/IConfig.ts
  src/core/config/schema/ConfigSchema.ts
  src/core/integrations/ApplePay.ts
  src/core/integrations/CardinalCommerce.ts
  src/core/integrations/VisaCheckout.ts
  src/core/shared/Notification.ts
  src/core/shared/Payment.ts
  src/json/config.json
  test/ST.spec.ts
  test/components/card-number/CardNumber.spec.ts
  test/components/control-frame/ControlFrame.spec.ts
  test/components/expiration-date/ExpirationDate.spec.ts
  test/components/security-code/SecurityCode.spec.ts
  test/core/classes/CardFrames.spec.ts
  test/core/classes/CommonFrames.spec.ts
  test/core/classes/MerchantFields.spec.ts
  test/core/classes/StCodec.spec.ts
  test/core/classes/StTransport.spec.ts
  test/core/integrations/ApplePay.spec.ts
  test/core/integrations/ApplePayMock.spec.ts
  test/core/integrations/CardinalCommerce.spec.ts
  test/core/integrations/CardinalCommerceMock.spec.ts
  test/core/integrations/VisaCheckout.spec.ts
  test/core/integrations/VisaCheckoutMock.spec.ts
  test/core/shared/FormField.spec.ts
  test/core/shared/Formatter.spec.ts
  test/core/shared/Notification.spec.ts
  test/core/shared/Payment.spec.ts
  test/core/shared/Validation.spec.ts
Labels: enhancement, javascript

#846 feature/ST-550-improve-styling-of-notification-frame
  package-lock.json
  src/ST.ts
  src/components/control-frame/ControlFrame.ts
  src/components/index.html
  src/components/index.ts
  src/components/notification-frame/NotificationFrame.ts
  src/components/notification-frame/notification-frame.html
  src/components/notification-frame/notification-frame.ts
  src/core/classes/CommonFrames.class.ts
  src/core/classes/StCodec.class.ts
  src/core/integrations/ApplePay.ts
  src/core/integrations/CardinalCommerce.ts
  src/core/integrations/VisaCheckout.ts
  src/core/services/Element.ts
  src/core/services/notification/NotificationService.ts
  src/core/shared/Notification.ts
  src/core/shared/Payment.ts
  src/core/shared/Selectors.ts
  src/core/styles/_core.scss
  src/core/styles/notification-frame.scss
  src/json/config.json
  test/components/control-frame/ControlFrame.spec.ts
  test/components/notification-frame/NotificationFrame.spec.ts
  test/core/Element.spec.ts
  test/core/classes/CommonFrames.spec.ts
  test/core/integrations/ApplePay.spec.ts
  test/core/integrations/CardinalCommerce.spec.ts
  test/core/shared/Notification.spec.ts
  test/core/shared/NotificationService.spec.ts
Labels: enhancement, javascript

#862 patches-for-low-vulnerabilities
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, javascript

#863 feature/ST-562-huskyjs-lint-staged-for-unifying-code-format
  example/json/config.json
  package.json
  src/application/components/card-number/CardNumber.spec.ts
  src/application/components/expiration-date/ExpirationDate.spec.ts
  src/application/components/security-code/SecurityCode.spec.ts
  src/client/ST.spec.ts
  src/client/config/ConfigResolver.ts
  src/client/config/schema/ConfigSchema.ts
  src/shared/model/config/IConfig.ts
Labels: enhancement, javascript

#865 release-2.0.7 - failing UT - lack of optional case
  src/core/config/model/IComponentsIds.ts
  src/core/shared/Notification.ts
Labels: bug, javascript

#882 STJS-592 - Revert out of frictionless fix to fix updateJWT for currency change
  CHANGELOG.md
  package-lock.json
  package.json
  src/core/shared/Payment.ts
Labels: bug, javascript
