Repository SecureTrading/js-payments, pull requests merged in 2020-04, with the labels that each got.

#886 sync-develop-with-master
  CHANGELOG.md
  example/json/config.json
  package-lock.json
  package.json
  src/application/components/index.html
  src/application/core/shared/Notification.ts
  src/client/ST.ts
  src/client/classes/CommonFrames.class.ts
  src/client/classes/CommonFrames.spec.ts
  src/shared/model/config/IComponentsIds.ts
  src/shared/model/config/IConfig.ts
  webpack.common.js
Labels: javascript

#890 bugfix/STJS-547-security-code-re-enabled-if-server-error-on-piba
  example/json/config.json
  package-lock.json
  src/application/components/card-number/CardNumber.ts
  src/application/components/security-code/SecurityCode.ts
Labels: bug, javascript

#891 Release/2.0.9 -> dev
  CHANGELOG.md
  example/json/config.json
  package-lock.json
  package.json
  src/application/components/control-frame/ControlFrame.ts
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/services/StCodec.class.ts
  src/application/core/services/StCodec.spec.ts
  src/application/core/services/StTransport.class.ts
  src/application/core/shared/Payment.ts
  src/client/classes/CommonFrames.class.ts
Labels: javascript

#887 feature/ST-567-ensure-that-full-tests-are-stable
  .travis.yml
Labels: enhancement, submodules

#909 fix-vulnerabilities-after-updates + bump js-payments-card package
  package-lock.json
  package.json
Labels: dependencies, javascript

#894 feature/STJS-590-change-example-to-pass-callbacks-in-config
  example/index.html
Labels: enhancement, javascript

#910 [WIP] ST-567-ensure-that-full-tests-are-stable
  .travis.yml
Labels: enhancement, submodules

#889 STJS-575 cybertonica tid passed in requests
  .travis.yml
  example/json/config.json
  polyfills.ts
  src/application/components/control-frame/ControlFrame.spec.ts
  src/application/components/control-frame/ControlFrame.ts
  src/application/core/integrations/Cybertonica.ts
  src/application/core/integrations/ICybertonica.ts
  src/application/core/models/IStRequest.ts
  src/application/core/models/cybertonica/IAFCybertonica.ts
  src/application/core/services/ConfigProvider.ts
  src/application/core/shared/Payment.spec.ts
  src/application/core/shared/Payment.ts
  src/bootstrap.ts
  src/client/ST.ts
  src/client/config/ConfigResolver.ts
  src/client/config/schema/ConfigSchema.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/shared/model/config/IConfig.ts
  src/testing/ServicesOverrides.ts
  src/testing/mocks/CybertonicaMock.ts
  webpack.prod.js
Labels: enhancement, javascript

#911 bugfix/STJS-607-visa-doesnt-work-on-develop
  example/json/config.json
  package-lock.json
  report.20200414.220004.12204.0.001.json
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/integrations/ApplePayMock.spec.ts
  src/application/core/integrations/VisaCheckout.spec.ts
  src/application/core/integrations/VisaCheckout.ts
  src/application/core/integrations/VisaCheckoutMock.spec.ts
  src/client/ST.ts
  src/client/config/ConfigResolver.ts
Labels: bug, javascript

#914 bugfix/STJS-609-security-code-doesnt-work-for-amex
  src/application/components/security-code/SecurityCode.spec.ts
  src/application/components/security-code/SecurityCode.ts
  src/application/core/models/constants/config-resolver/DefaultPlaceholders.ts
  src/client/config/ConfigResolver.ts
Labels: bug, javascript

#929 feature/STJS-609-placeholders-for-fields
  example/json/config.json
  src/client/config/ConfigResolver.ts
  src/shared/model/config/IConfig.ts
  src/shared/model/config/IPlaceholdersConfig.ts
Labels: enhancement, javascript

#895 feature/STJS-602-config-resolver-class-default-config-check
  example/json/config.json
  package-lock.json
  report.20200414.220004.12204.0.001.json
  src/application/core/integrations/ApplePay.ts
  src/application/core/models/IApplePay.ts
  src/application/core/models/IVisaSettings.ts
  src/application/core/models/constants/IVisaCheckout.ts
  src/application/core/models/constants/config-resolver/DefaultApmsRequestTypes.ts
  src/application/core/models/constants/config-resolver/DefaultComponents.ts
  src/application/core/models/constants/config-resolver/DefaultComponentsIds.ts
  src/application/core/models/constants/config-resolver/DefaultComponentsRequestTypes.ts
  src/application/core/models/constants/config-resolver/DefaultConfig.ts
  src/application/core/models/constants/config-resolver/DefaultFieldsToSubmit.ts
  src/application/core/models/constants/config-resolver/DefaultInit.ts
  src/application/core/models/constants/config-resolver/DefaultPlaceholders.ts
  src/application/core/models/constants/config-resolver/DefaultRequestTypes.ts
  src/application/core/models/constants/config-resolver/DefaultSubmitFields.ts
  src/client/ST.ts
  src/client/config/ConfigResolver.spec.ts
  src/client/config/ConfigResolver.ts
  src/client/config/schema/ConfigSchema.ts
  src/shared/model/config/IConfig.ts
  src/shared/model/config/IPlaceholdersConfig.ts
Labels: enhancement, javascript

#942 Iframe useless extra space when card is hidden
  example/json/config.json
  example/style.scss
Labels: bug, javascript

#944 Security code checking fix
  example/json/config.json
  src/application/components/security-code/SecurityCode.spec.ts
  src/application/components/security-code/SecurityCode.ts
  src/application/core/models/constants/config-resolver/DefaultPlaceholders.ts
  src/application/core/shared/MessageBus.spec.ts
  src/application/core/shared/MessageBus.ts
  src/client/config/ConfigResolver.spec.ts
  src/testing/mocks/MessageBusMock.ts
  tslint.json
Labels: bug, javascript

#946 Incrtease code coverage
  src/application/core/shared/Notification.spec.ts
Labels: enhancement, javascript

#943 bugfix/STJS-546-form-locking-says-as-processing-if-request-types-threedquery
  example/json/config.json
  src/application/components/control-frame/ControlFrame.ts
Labels: bug, javascript

#913 feature/STJS-597-add-submit-on-cancel-for-cancelled-payments
  example/index.html
  example/json/config.json
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/integrations/VisaCheckout.spec.ts
  src/application/core/integrations/VisaCheckout.ts
  src/application/core/models/constants/NotificationType.ts
  src/application/core/models/constants/config-resolver/DefaultConfig.ts
  src/application/core/shared/MessageBus.ts
  src/application/core/shared/Notification.ts
  src/application/core/shared/Selectors.ts
  src/client/ST.ts
  src/client/classes/CommonFrames.class.ts
  src/client/classes/CommonFrames.spec.ts
  src/client/classes/notification/NotificationService.ts
  src/client/config/ConfigResolver.spec.ts
  src/client/config/ConfigResolver.ts
  src/client/config/schema/ConfigSchema.ts
  src/client/shared/NotificationService.spec.ts
  src/shared/model/config/IConfig.ts
  src/styles/_variables.scss
  src/styles/notification.css
Labels: enhancement, javascript

#947 feature/STJS-461-support-apple-pay-visa-checkout-with-cybertonica
  example/json/config.json
  src/application/core/integrations/Cybertonica.ts
  src/application/core/models/constants/config-resolver/DefaultConfig.ts
  src/application/core/shared/Payment.spec.ts
  src/client/config/ConfigResolver.spec.ts
  src/client/config/ConfigResolver.ts
Labels: enhancement, javascript

#966 feature/STJS-622-remove-unused-properties-in-config
  example/json/config.json
  src/application/core/integrations/CardinalCommerce.ts
  src/application/core/models/constants/config-resolver/DefaultConfig.ts
  src/client/ST.ts
  src/client/config/ConfigResolver.spec.ts
  src/client/config/ConfigResolver.ts
  src/client/config/schema/ConfigSchema.ts
  src/shared/model/config/IConfig.ts
Labels: enhancement, javascript
