Repository SecureTrading/js-payments, pull requests merged in 2020-06, with the labels that each got.

#1075 hotfix/STJS-656-apple-pay-remove-handler-from-button
  CHANGELOG.md
  example/json/config.json
  package.json
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/services/StTransport.spec.ts
  src/client/classes/CommonFrames.class.ts
Labels: bug, javascript

#1079 release/2.2.1
  CHANGELOG.md
  example/json/config.json
  example/style.scss
  package.json
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/services/StTransport.spec.ts
  src/client/ST.ts
  src/client/classes/CommonFrames.class.ts
  src/styles/_control-frame.css
Labels: enhancement, javascript

#1083 release/2.2.2
  CHANGELOG.md
  example/json/config.json
  package.json
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
Labels: bug, javascript

#1084 bugfix/STJS-617-merchants-styles-breaks-cardinal-styling
  example/json/config.json
  src/application/components/control-frame/control-frame.scss
  src/styles/_control-frame.css
Labels: bug, javascript

#1100 [WIP] bugfix/STJS-673-notification-banner
  package-lock.json
  src/application/core/models/constants/notifications/NotificationsClasses.ts
  src/application/core/models/constants/notifications/NotificationsMessageTypes.ts
  src/application/core/shared/Notification.ts
  webpack.common.js
Labels: bug, javascript

#1081 feature/STJS-633-national-zakat-foundation-block-form
  src/application/core/integrations/cardinal-commerce/CardinalCommerce.ts
  src/application/core/models/constants/FormState.ts
  src/application/core/shared/EventTypes.ts
  src/client/ST.ts
  src/client/classes/CardFrames.class.ts
  src/client/classes/CardFrames.spec.ts
  src/testing/mocks/CardinalMock.ts
Labels: enhancement, javascript

#1115 [WIP] feature/STJS-672-adjust-to-jwt-generator
  .gitignore
  example/index.html
  example/index.ts
  example/json/config.json.dist
  example/json/jwtdata.json.dist
  package-lock.json
  package.json
  src/application/core/models/constants/IVisaCheckout.ts
Labels: enhancement, javascript

#1130 addjusted travis jobs
  .travis.yml
  example/index.html
Labels: enhancement, submodules

#1145 [WIP] feature/STJS-685-add-fallback-lang
  package-lock.json
  package.json
  src/application/core/integrations/Cybertonica.spec.ts
  src/client/ST.ts
Labels: enhancement, javascript
