Repository SecureTrading/js-payments, pull requests merged in 2020-05, with the labels that each got.

#968 feature/STJS-622-standalone-cybertonica-implementation
  example/index.html
  example/json/config.json
  src/application/components/control-frame/ControlFrame.ts
  src/application/core/integrations/Cybertonica.ts
  src/application/core/shared/MessageBus.ts
  src/client/ST.ts
Labels: enhancement, javascript

#928 feature/STJS-573-move-cardinal-to-control-frame
  example/index.html
  example/json/config.json
  src/application/components/card-number/CardNumber.ts
  src/application/components/control-frame/ControlFrame.spec.ts
  src/application/components/control-frame/ControlFrame.ts
  src/application/components/security-code/SecurityCode.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/integrations/CardinalCommerce.spec.ts
  src/application/core/integrations/CardinalCommerce.ts
  src/application/core/integrations/CardinalCommerceMock.spec.ts
  src/application/core/integrations/CardinalCommerceMock.ts
  src/application/core/integrations/VisaCheckout.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerce.spec.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerce.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerceTokensProvider.ts
  src/application/core/integrations/cardinal-commerce/CardinalProvider.ts
  src/application/core/integrations/cardinal-commerce/ICardinal.ts
  src/application/core/integrations/cardinal-commerce/ICardinalCommerceTokens.ts
  src/application/core/integrations/cardinal-commerce/ICardinalProvider.ts
  src/application/core/integrations/cardinal-commerce/ThreeDInitRequest.ts
  src/application/core/models/IAuthorizePaymentResponse.ts
  src/application/core/models/ISubmitData.ts
  src/application/core/services/StTransport.class.ts
  src/application/core/services/StTransport.spec.ts
  src/application/core/shared/FormField.ts
  src/application/core/shared/Frame.ts
  src/application/core/shared/MessageBus.ts
  src/application/core/shared/Payment.spec.ts
  src/application/core/shared/Payment.ts
  src/application/core/shared/Validation.spec.ts
  src/application/core/shared/Validation.ts
  src/client/ST.spec.ts
  src/client/ST.ts
  src/client/classes/CardFrames.class.ts
  src/client/classes/CardFrames.spec.ts
  src/client/classes/CommonFrames.class.ts
  src/styles/_control-frame.css
  src/testing/ServicesOverrides.ts
  src/testing/mocks/CardinalMock.ts
  src/testing/mocks/MessageBusMock.ts
  src/testing/mocks/MockCardinalProvider.ts
Labels: enhancement, javascript

#988 [WIP] Feature/stjs 625 destroy spa
  example/json/config.json
  package-lock.json
  src/application/components/control-frame/ControlFrame.spec.ts
  src/application/components/control-frame/ControlFrame.ts
  src/application/components/control-frame/control-frame.ts
  src/application/core/shared/EventTypes.ts
  src/application/core/shared/MessageBus.ts
  src/application/core/shared/Notification.spec.ts
  src/application/core/shared/Notification.ts
  src/client/ST.ts
  src/client/classes/CommonFrames.class.ts
  src/client/classes/notification/NotificationService.ts
  src/client/config/ConfigService.ts
  src/environments/environment.prod.ts
  src/shared/services/message-bus/FramesHub.ts
  src/shared/services/message-bus/InterFrameCommunicator.ts
  src/shared/services/storage/AbstractStorage.ts
Labels: enhancement, javascript

#1004 fixed frame url param in prod environment
  src/environments/environment.prod.ts
Labels: bug, javascript

#1009 fixes-on-release-branch
  example/json/config.json
  src/application/components/control-frame/ControlFrame.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerce.ts
  src/client/ST.ts
Labels: javascript

#1008 bugfix/STJS-648-submitoncancel-doesnt-work-on-apple-pay
  example/json/config.json
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/models/IApplePay.ts
  src/application/core/models/IApplePayConfig.ts
  src/client/ST.spec.ts
  src/client/ST.ts
  src/client/classes/CommonFrames.class.ts
  src/client/classes/CommonFrames.spec.ts
  src/client/config/ConfigResolver.spec.ts
  src/client/config/ConfigResolver.ts
  src/client/config/schema/ConfigSchema.ts
Labels: bug, javascript

#1001 feature/STJS-624-detect-payment-type-when-using-parenttransactionreference
  example/json/config.json
  src/application/components/control-frame/ControlFrame.spec.ts
  src/application/components/control-frame/ControlFrame.ts
  src/application/components/security-code/SecurityCode.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerceTokensProvider.ts
  src/application/core/shared/Payment.ts
Labels: bug, javascript

#1038 fix-packages-vulns
  package-lock.json
Labels: bug, dependencies, javascript

#1013 bugfix/2.0.2-all-fixes
  example/index.html
  example/json/config.json
  package-lock.json
  package.json
  src/application/components/control-frame/ControlFrame.spec.ts
  src/application/components/control-frame/ControlFrame.ts
  src/application/components/security-code/SecurityCode.spec.ts
  src/application/components/security-code/SecurityCode.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerceTokensProvider.ts
  src/application/core/models/IThreeDInitResponse.ts
  src/application/core/models/constants/config-resolver/DefaultPlaceholders.ts
  src/application/core/shared/EventTypes.ts
  src/application/core/shared/MessageBus.spec.ts
  src/application/core/shared/MessageBus.ts
  src/application/core/shared/Payment.ts
  src/client/ST.ts
  src/client/classes/CardFrames.class.ts
  src/client/classes/CardFrames.spec.ts
  src/client/config/ConfigResolver.spec.ts
  src/client/config/schema/ConfigSchema.ts
  webpack.common.js
Labels: bug, javascript

#1041 feature/STJS-649-manual-update-of-js-payments-card-package
  package-lock.json
  package.json
Labels: enhancement, javascript

#1055 removed error on update jwt
  src/application/components/security-code/SecurityCode.ts
  src/application/core/integrations/cardinal-commerce/CardinalCommerce.spec.ts
Labels: bug, javascript

#1058 Hotfix/failed 3ds error not redirecting
  src/application/core/integrations/cardinal-commerce/CardinalCommerce.ts
Labels: bug, javascript

#1057 bugfix/denial-ofs-service-vuln
  package-lock.json
Labels: bug, dependencies, javascript

#1060 feature/STJS-578-implement-lgtm-suggestions
  example/receipt.html
  src/application/core/integrations/ApplePay.ts
  src/application/core/models/constants/config-resolver/DefaultConfig.ts
  src/client/classes/CardFrames.class.ts
Labels: enhancement, javascript

#1063 feature/STJS-665-add-changelog-notes-for-2.2.0
  CHANGELOG.md
Labels: enhancement
