Repository SecureTrading/js-payments, pull requests merged in 2020-07, with the labels that each got.

#1150 bugfix/STJS-691-updatejwt-to-set-amex-card-as-parent-does-not-update-securitycode-field
  src/application/components/security-code/SecurityCode.spec.ts
  src/application/components/security-code/SecurityCode.ts
  src/application/core/models/constants/SecurityCode.ts
Labels: bug, javascript

#1169 synchronize develop with master
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/ST.ts
  src/client/classes/CardFrames.class.ts
Labels: javascript

#1183 added additional popup for testing purpose
  example/index.html
Labels: enhancement, javascript

#1201 bugfix/callback-called-twice-in-apple-pay
  src/application/core/integrations/ApplePay.ts
Labels: bug, javascript

#1199 [WIP] bugfix/STJS-753-react-js-switching-tab-issue
  src/application/core/integrations/cardinal-commerce/CardinalProvider.ts
Labels: bug, javascript

#1185 [WIP] release/2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/application/components/control-frame/ControlFrame.spec.ts
  src/application/components/control-frame/ControlFrame.ts
  src/application/components/control-frame/control-frame.ts
  src/application/components/security-code/SecurityCode.spec.ts
  src/application/components/security-code/SecurityCode.ts
  src/application/core/integrations/ApplePay.spec.ts
  src/application/core/integrations/ApplePay.ts
  src/application/core/integrations/ApplePayMock.spec.ts
  src/application/core/integrations/VisaCheckout.spec.ts
  src/application/core/integrations/cardinal-commerce/CardinalProvider.ts
  src/application/core/models/IStorage.ts
  src/application/core/services/ConfigProvider.ts
  src/application/core/shared/DomMethods.ts
  src/application/core/shared/EventTypes.ts
  src/application/core/shared/Notification.spec.ts
  src/application/core/shared/Notification.ts
  src/application/core/shared/Payment.spec.ts
  src/application/core/store/IAction.ts
  src/application/core/store/IActionsMap.ts
  src/application/core/store/IState.ts
  src/application/core/store/Store.spec.ts
  src/application/core/store/Store.ts
  src/application/core/store/StoreAccessor.spec.ts
  src/application/core/store/StoreAccessor.ts
  src/application/core/store/StoreFactory.spec.ts
  src/application/core/store/StoreFactory.ts
  src/application/core/store/createReducer.ts
  src/application/core/store/epics/dummyEpic.ts
  src/application/core/store/operators/ofType.spec.ts
  src/application/core/store/operators/ofType.ts
  src/application/core/store/reducers/config/ConfigActions.ts
  src/application/core/store/reducers/config/ConfigReducer.spec.ts
  src/application/core/store/reducers/config/ConfigReducer.ts
  src/application/core/store/reducers/config/IConfigState.ts
  src/application/core/store/reducers/storage/IStorageState.ts
  src/application/core/store/reducers/storage/StorageActions.ts
  src/application/core/store/reducers/storage/StorageReducer.spec.ts
  src/application/core/store/reducers/storage/StorageReducer.ts
  src/client/ST.ts
  src/client/config/ConfigService.spec.ts
  src/client/config/ConfigService.ts
  src/shared/interfaces/IControlFrameWindow.ts
  src/shared/services/message-bus/FrameAccessor.ts
  src/shared/services/storage/BrowserLocalStorage.ts
  src/shared/services/storage/IStorage.ts
  src/shared/services/storage/ISynchronizedStorage.ts
  src/shared/services/storage/ParentFrameStorage.ts
  src/shared/services/storage/SimpleStorage.ts
  src/shared/services/storage/StoreBasedStorage.ts
  webpack.dev.js
Labels: javascript

#1203 sync-develop-with-master
  CHANGELOG.md
  package-lock.json
  package.json
  src/application/core/integrations/ApplePay.ts
  src/application/core/integrations/cardinal-commerce/CardinalProvider.ts
  src/shared/services/storage/ParentFrameStorage.ts
  src/shared/services/storage/StoreBasedStorage.ts
Labels: enhancement, javascript

#1217 [WIP] feature/STJS-675-issue-with-panicon
  src/application/core/shared/input/Input.ts
  src/styles/_core.scss
Labels: enhancement, javascript

#1218 dot-prop-severe-vuln
  package.json
Labels: dependencies, javascript, security
